# Generated by Django 3.2.4 on 2021-12-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variation',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
