# Generated by Django 3.2.4 on 2021-12-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'prooductgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
