# Generated by Django 3.2.4 on 2022-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220503_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='usage_times',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
